# Variables are bound to objects only after the objects are created, but when the exception happens, the following code no longer works.
```
class Gizmo:
    def __init__(self):
        print(f'Gizmo id: {id(self)}')
        
x = Gizmo() # Gizmo id: 4301489152
y = Gizmo() * 10 
# Output: Gizmo id: 4301489432
# This id belongs to y. Line 8 creates an instance Gizmo() first, then the code meets unsupported operand. But the new Gizmo object is already there.

```

# Identity, Equality, and Aliases
#### A dictionary can have several different alias which are bound to exactly the same data structure. They are of the same content, even with the same id.
But, they are different things. 
```
charles = {'name': 'Charles L. Dodgson', 'born': 1832}
lewis = charles
print(charles==lewis) # True
print(charles is not lewis) # True
```

