>>> t=(1,2,[30,40])
>>> t[2]+=[50,60]

t 变成 (1, 2, [30, 40, 50, 60])。
因为 tuple 不支持对它的元素赋值,所以会抛出 TypeError 异常。
没人料到的结果:t[2] 被改动了,但是也有异常抛出

这其实是个非常罕见的边界情况,在 15 年的 Python 生涯中,我还没见过谁在这个地方吃
过亏。
至此我得到了 3 个教训。
• 不要把可变对象放在元组里面。
• 增量赋值不是一个原子操作。我们刚才也看到了,
 它虽然抛出了异常,但还是完成了操作。
•
 查看
 Python
 的字节码并不难,而且它对我们了解代码背后的运行机制很有帮助。
